import cv2
import os
import json
import sys
from dotenv import load_dotenv

# Add parent dir to path to import AeroSentinel
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import AeroSentinel.AeroSentinel as AeroSentinel

def initialize_gemini():
    try:
        import google.generativeai as genai
    except ImportError:
        print("Error: google-generativeai package not installed. Please run: pip install google-generativeai")
        sys.exit(1)
        
    env_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), '.env')
    load_dotenv(env_path)
    api_key = os.getenv("GEMINI_API_KEY")
    
    if not api_key:
        print(f"Error: GEMINI_API_KEY not found in .env at {env_path}")
        sys.exit(1)
        
    genai.configure(api_key=api_key)
    # Using gemini-1.5-pro-latest for vision + reasoning (Gemini 3.1 Pro capabilities)
    model = genai.GenerativeModel('gemini-1.5-pro-latest')
    return model

def capture_frames(num_frames=1):
    import time
    from PIL import Image
    frame_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'latest_frame.jpg')
    
    # Wait for the frame to be generated by AeroCameraStream
    max_retries = 20
    while not os.path.exists(frame_path) and max_retries > 0:
        time.sleep(0.5)
        max_retries -= 1
        
    if not os.path.exists(frame_path):
        print(f"Error: Frame not found at {frame_path}")
        return []
        
    try:
        # Open the image saved by the stream server
        img = Image.open(frame_path)
        # Force load to ensure it's fully read
        img.load()
        return [img]
    except Exception as e:
        print(f"Error reading frame: {e}")
        return []

def analyze_traffic_state(model, frames):
    prompt = """
    You are AeroSight, an advanced visual reasoning AI agent for the AeroSmart city system.
    Analyze the provided frame(s) from a traffic/laptap camera.
    Output ONLY a JSON object with two keys:
    "points": an integer representing the heavy tokens awarded or deducted based on the visual behavior. (e.g., +5 for safe environment/clear road, -10 for dangerous behavior or obstacles).
    "message": a rich descriptive text in Arabic of what is happening (e.g., "ملاك تقود بهدوء، لا توجد عوائق، المسار الأخضر متاح" or "شخص يظهر أمام الكاميرا بحالة طبيعية").

    Ensure the response is valid JSON and nothing else.
    """
    
    try:
        # Pass the frames and the prompt to the model
        response = model.generate_content([prompt, *frames], generation_config={"max_output_tokens": 150, "temperature": 0.2})
        text_response = response.text
        
        # Clean up markdown if present
        if text_response.startswith("```json"):
            text_response = text_response.strip("```json").strip("```").strip()
        elif text_response.startswith("```"):
            text_response = text_response.strip("```").strip()
            
        result = json.loads(text_response)
        return result
    except Exception as e:
        print(f"Error during Gemini analysis: {e}")
        # Fallback if API fails or parsing fails
        return {"points": 5, "message": "تحليل بصري افتراضي: النظام يعمل والمسار متاح"}

def main():
    print("AeroSight [👁️]: Initializing AI Model (Gemini 3.1 Pro)...")
    model = initialize_gemini()
    
    print("AeroSight [👁️]: Capturing real-time frame from local camera...")
    frames = capture_frames(num_frames=1)
    
    if not frames:
        print("AeroSight [👁️]: Failed to capture frames. Exiting.")
        return
        
    print("AeroSight [👁️]: Analyzing visual data with deep reasoning...")
    result_json = analyze_traffic_state(model, frames)
    
    print("AeroSight [👁️]: Extraction Complete. Passing data to AeroSentinel [🧠] with low latency...\n")
    
    # Initialize DB connection via AeroSentinel
    db_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'district_pulse.db')
    db_conn = AeroSentinel.initialize_database(db_name=db_path)
    
    # Get active district dynamically
    import AeroNavigator.AeroNavigator as AeroNavigator
    active_district = AeroNavigator.get_active_district()
    print(f"AeroSight [👁️]: Active District resolved to '{active_district}'.")
    
    # Process the data
    AeroSentinel.process_aerosight_data(db_conn, result_json, district_name=active_district)
    
    db_conn.close()

if __name__ == "__main__":
    main()
